### ISSUE TITLE
Conversion from iterator to bool

### ISSUE THREAD

**Issue by JBenda** [iLCSoft/MarlinMT#11]
- Package version: commit: c8d0235a

function `exist` in `Extensions.h:85` returns map iterator instead of bool.
probably should be: `find(…) != _extensions.end()`

[std::map<…>::find](https://en.cppreference.com/w/cpp/container/map/find)

gcc message
> /afs/desy.de/user/b/bendajul/public/MarlinMT/source/./include/marlin/Extensions.h:85:71: error: cannot convert ‘std::map<long unsigned int, std::shared_ptr<marlin::Extension> >::const_iterator’ {aka ‘std::_Rb_tree_const_iterator<std::pair<const long unsigned int, std::shared_ptr<marlin::Extension> > >’} to ‘bool’ in return
       return _extensions.find( std::type_index(typeid(K)).hash_code() ) ;

**Comment by rete** [comment]
Fixed in #13. Closing
